map_type: costmap


#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 2.0
obstacle_range: 3.5
raytrace_range: 4.0

robot_radius: 0.18


footprint_padding: 0.1

update_frequency: 5.0

plugin:
  - {name: static_layer , type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer , type: "costmap_2d::VoxelLayer"}
  # - {name: inflation_layer , type: "costmap_2d::InflationLayer"}

static_layer:
  enabled: true
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.2
  update_frequency: 5.0
  rolling_window: false
  always_send_full_costmap: true
  lethal_cost_threshold: 65
  map_topic: map

obstacle_layer:
  enabled: true
  max_obstacle_height: 6.0
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: false
  observation_sources: scan_laser
  
  scan_laser:
    topic: scan
    sensor_frame: base_scan
    data_type: LaserScan
    observation_persistence: 0.0
    expected_update_rate: 0.3
    max_obstacle_height: 5.0
    min_obstacle_height: 0.0
    obstacle_range: 2.5
    raytrace_range: 3.0