local_costmap:

  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.02

  plugin:
    - {name: static_layer , type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer , type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer , type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled: true
    inflation_radius: 0.5
    cost_scaling_factor: 10.0